### ISSUE TITLE
This doesnt work

### ISSUE THREAD

**Issue by ghost** [Yogpod/redandblackgmod#4]
I see the gray background and the gmod logo, but once I hit the actual screen I dont see anything changed...

![image](https://user-images.githubusercontent.com/54610688/80292033-7fb8be00-8718-11ea-9c36-d83ef0d07821.png)

![image](https://user-images.githubusercontent.com/54610688/80292042-9bbc5f80-8718-11ea-97e2-2bcf063b40f5.png)

**Comment by Yogpod** [comment]
whenever there’s an update or you verify your gmod files you have to reinstall

**Comment by ghost** [comment]
This is my first time downloading it, It should be fresh.

**Comment by Yogpod** [comment]
works on x64, gonna go test on x32 now

**Comment by Yogpod** [comment]
works fine on x32

**Comment by Yogpod** [comment]
works fine on x32

**Comment by Yogpod** [comment]
https://propkill.me/pls/fc8kme.mp4

**Comment by ghost** [comment]
I feel really dumb right now... I put it in /garrysmod/ not /garrysmod/garrysmod...
